//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmutPizzam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public string KullaniciAdi { get; set; }
        public string Email { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> YorumTarihi { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual Menuler Menuler { get; set; }
    }
}
